name: '${project_name}'
version: '${version}'
main: dev.debutter.cuberry.paper.Paper
api-version: '1.20'
author: 'ButterDebugger'
description: '${project_description}'
website: '${project_url}'

softdepend:
  - PlaceholderAPI
  - ProtoWeaver

commands:
  cuberry:
    description: The Cuberry command
    aliases:
      - cubefruit
      - fruit
      - cf
      - cb

permissions:
  cuberry.*:
    description: Grants you every permission
    default: false
    children:
      cuberry.admin: true
  cuberry.admin:
    description: Allows you to run admin commands
    default: op
    children:
      cuberry.alerts.joinattempt: true
      cuberry.alerts.report: true
      cuberry.alerts.commands: true
      cuberry.mutechat.bypass: true
      cuberry.idle-kick.bypass: true

  cuberry.formattable-text.signs.*:
    description: Allows you to colorize your signs with any MiniMessage tag
    children:
      cuberry.formattable-text.signs.color: true
      cuberry.formattable-text.signs.decoration: true
      cuberry.formattable-text.signs.gradient: true
      cuberry.formattable-text.signs.dynamic: true
      cuberry.formattable-text.signs.interactive: true
  cuberry.formattable-text.signs.color:
    description: Allows you to colorize your signs with any color MiniMessage tags
  cuberry.formattable-text.signs.decoration:
    description: Allows you to colorize your signs with any decoration MiniMessage tags
  cuberry.formattable-text.signs.gradient:
    description: Allows you to colorize your signs with any gradient MiniMessage tags
  cuberry.formattable-text.signs.dynamic:
    description: Allows you to colorize your signs with any dynamic MiniMessage tags
  cuberry.formattable-text.signs.interactive:
    description: Allows you to colorize your signs with any interactive MiniMessage tags

  cuberry.formattable-text.books.*:
    description: Allows you to colorize your books with any MiniMessage tag
    children:
      cuberry.formattable-text.books.color: true
      cuberry.formattable-text.books.decoration: true
      cuberry.formattable-text.books.gradient: true
      cuberry.formattable-text.books.dynamic: true
      cuberry.formattable-text.books.interactive: true
  cuberry.formattable-text.books.color:
    description: Allows you to colorize your books with any color MiniMessage tags
  cuberry.formattable-text.books.decoration:
    description: Allows you to colorize your books with any decoration MiniMessage tags
  cuberry.formattable-text.books.gradient:
    description: Allows you to colorize your books with any gradient MiniMessage tags
  cuberry.formattable-text.books.dynamic:
    description: Allows you to colorize your books with any dynamic MiniMessage tags
  cuberry.formattable-text.books.interactive:
    description: Allows you to colorize your books with any interactive MiniMessage tags

  cuberry.chat.colorize.*:
    description: Allows you to colorize your messages with any MiniMessage tag
    children:
      cuberry.chat.colorize.color: true
      cuberry.chat.colorize.decoration: true
      cuberry.chat.colorize.gradient: true
      cuberry.chat.colorize.dynamic: true
      cuberry.chat.colorize.interactive: true
  cuberry.chat.colorize.color:
    description: Allows you to colorize your messages with any color MiniMessage tags
  cuberry.chat.colorize.decoration:
    description: Allows you to colorize your messages with any decoration MiniMessage tags
  cuberry.chat.colorize.gradient:
    description: Allows you to colorize your messages with any gradient MiniMessage tags
  cuberry.chat.colorize.dynamic:
    description: Allows you to colorize your messages with any dynamic MiniMessage tags
  cuberry.chat.colorize.interactive:
    description: Allows you to colorize your messages with any interactive MiniMessage tags

  cuberry.alerts.joinattempt:
    description: Allows you to see join attempt messages
  cuberry.alerts.report:
    description: Allows you to receive new reports
  cuberry.idle-kick.bypass:
    description: Prevents you from being kicked for being afk

  cuberry.home:
    description: Allows you to teleport to your home
  cuberry.sethome:
    description: Allows you to set your home location
  cuberry.delhome:
    description: Allows you to remove your home location
  cuberry.message:
    description: Allows you to message other players
  cuberry.reply:
    description: Allows you to reply to players messages
  cuberry.itemstack:
    description: Allows you to modify items
  cuberry.respawn:
    description: Allows you to force respawn other players
  cuberry.skipday:
    description: Allows you to smoothly transition to day
  cuberry.spawn:
    description: Allows you to teleport to spawn
  cuberry.setspawn:
    description: Allows you to set the spawn location
  cuberry.tpa:
    description: Allows you to request a teleport to another player
  cuberry.tpahere:
    description: Allows you to request a teleport from another player to you
  cuberry.tpaccept:
    description: Allows you to accept tpa requests
  cuberry.tpadeny:
    description: Allows you to deny tpa requests
  cuberry.tpacancel:
    description: Allows you to cancel outgoing tpa requests
  cuberry.worldwhitelist:
    description: Allows you to manage world whitelists
  cuberry.gamemode:
    description: Allows you to change gamemodes
  cuberry.fly:
    description: Allows you to toggle flight
  cuberry.heal:
    description: Allows you to heal players
  cuberry.mutechat:
    description: Allows you to mute the chat
  cuberry.mutechat.bypass:
    description: Allows you to send message while the chat is muted
  cuberry.report:
    description: Allows you to make reports
  cuberry.whois:
    description: Allows you to see info about a player
  cuberry.rules:
    description: Allows you to read the server rules
  cuberry.warp:
    description: Allows you to teleport to warps
  cuberry.delwarp:
    description: Allows you to delete warps
  cuberry.setwarp:
    description: Allows you to create warps
  cuberry.listwarps:
    description: Allows you to list warps
  cuberry.tphere:
    description: Allows you to teleport players to you
  cuberry.tp2p:
    description: Allows you to teleport to players
  cuberry.tpall:
    description: Allows you to teleport all players to you
  cuberry.tpoffline:
    description: Allows you to teleport to players logout locations
  cuberry.sudo:
    description: Allows you to use the sudo command
  cuberry.back:
    description: Allows you to use the back command
  cuberry.enderchest:
    description: Allows you to use the enderchest command
  cuberry.top:
    description: Allows you to use the top command
  cuberry.action:
    description: Allows you to use the action command